// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgvalXHlpZsUZd8n9G6dkoQ5O7IAia-XA',
    appId: '1:1025877922533:web:f2812206f48a4d71eafa0c',
    messagingSenderId: '1025877922533',
    projectId: 'navbar-e51ee',
    authDomain: 'navbar-e51ee.firebaseapp.com',
    storageBucket: 'navbar-e51ee.appspot.com',
    measurementId: 'G-9JR1QKVV5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIYnLeslJhiljZnRgoI_-5jLDHZrXx9iA',
    appId: '1:1025877922533:android:d3dc379aeea81bf5eafa0c',
    messagingSenderId: '1025877922533',
    projectId: 'navbar-e51ee',
    storageBucket: 'navbar-e51ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9rqqAfKu2Ms9N6ycP1LQz3dMpsChjRKg',
    appId: '1:1025877922533:ios:17267c4ca9426ee9eafa0c',
    messagingSenderId: '1025877922533',
    projectId: 'navbar-e51ee',
    storageBucket: 'navbar-e51ee.appspot.com',
    iosClientId:
        '1025877922533-7hk0jufoh35km0u8o418ds9a8grqdbgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.collectarAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9rqqAfKu2Ms9N6ycP1LQz3dMpsChjRKg',
    appId: '1:1025877922533:ios:17267c4ca9426ee9eafa0c',
    messagingSenderId: '1025877922533',
    projectId: 'navbar-e51ee',
    storageBucket: 'navbar-e51ee.appspot.com',
    iosClientId:
        '1025877922533-7hk0jufoh35km0u8o418ds9a8grqdbgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.collectarAdmin',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgvalXHlpZsUZd8n9G6dkoQ5O7IAia-XA',
    appId: '1:1025877922533:web:f2812206f48a4d71eafa0c',
    messagingSenderId: '1025877922533',
    projectId: 'navbar-e51ee',
    authDomain: 'navbar-e51ee.firebaseapp.com',
    storageBucket: 'navbar-e51ee.appspot.com',
    measurementId: 'G-9JR1QKVV5P',
  );
}
